### ISSUE TITLE
Update-drafts goes Boom...

### ISSUE THREAD

**Issue by wkumari** [ekr/iphab#4]
1: Did setup and initial sync (might want to update instructions to suggest people disable email!).

2: Made some edits in web interface -- worked.

3: iphab.py download-review draft-ietf-ippm-2330-ipv6 -- worked.

4: then went boom:
```
$ iphab update-agenda
receiving file list ... done

sent 16 bytes  received 243321 bytes  97334.80 bytes/sec
total size is 169381561  speedup is 696.08
Switched to branch 'master'
Deleted branch upload (was 2922327).
Switched to a new branch 'upload'
awk: can't open file ids/draft-ali-spring-srv6-pm-02.txt
 source line number 55
Error: Command '['awk', '-f', '/Users/wkumari/src/github/iphab/strip.awk', 'ids/draft-ali-spring-srv6-pm-02.txt']' returned non-zero exit status 2
New drafts
Traceback (most recent call last):
  File "/usr/local/bin/iphab", line 507, in <module>
    update_agenda(RC["reviewer"])
  File "/usr/local/bin/iphab", line 207, in update_agenda
    assign_reviewers_from_agenda(agenda, [reviewer])
  File "/usr/local/bin/iphab", line 202, in assign_reviewers_from_agenda
    add_reviewer(rev, revision, blocking)
  File "/usr/local/bin/iphab", line 173, in add_reviewer
    "objectIdentifier":revision
  File "/usr/local/bin/iphab", line 152, in run_call_conduit
    raise "Error doing call-conduit: %s"%err
TypeError: exceptions must be old-style classes or derived from BaseException, not str

$ iphab update-drafts
receiving file list ... done

sent 16 bytes  received 243321 bytes  97334.80 bytes/sec
total size is 169381561  speedup is 696.08
Switched to branch 'master'
Deleted branch upload (was 2922327).
Switched to a new branch 'upload'
awk: can't open file ids/draft-ali-spring-srv6-pm-02.txt
 source line number 55
Error: Command '['awk', '-f', '/Users/wkumari/src/github/iphab/strip.awk', 'ids/draft-ali-spring-srv6-pm-02.txt']' returned non-zero exit status 2
New drafts
```

Yup, I have no draft-ali-spring-srv6-pm:
```
ls ids/draft-ali-spring-*.txt
ids/draft-ali-spring-bfd-sr-policy-00.txt         ids/draft-ali-spring-sr-traffic-accounting-02.txt ids/draft-ali-spring-srv6-oam-00.txt
```

I thought that that is what update-drafts did?

**Comment by ekr** [comment]
Probably this is mis-sync between the index and the drafts. I changed this to use the directory listing, which ought to help?
